/*
  Copyright AyanWorks Technology Solutions Pvt. Ltd. All Rights Reserved.
  SPDX-License-Identifier: Apache-2.0
*/

export enum PresentationState {
  STATE_REQUEST_SENT = "STATE_REQUEST_SENT",
  STATE_REQUEST_RECEIVED = "STATE_REQUEST_RECEIVED",
  STATE_PRESENTATION_SENT = "STATE_PRESENTATION_SENT",
  STATE_PRESENTATION_RECEIVED = "STATE_PRESENTATION_RECEIVED",
  STATE_VERIFIED = "STATE_VERIFIED",
  STATE_PRESENTATION_ACKED = "STATE_PRESENTATION_ACKED",
  STATE_PROPOSAL_SENT = "STATE_PROPOSAL_SENT"
}
